export const WORKOUTS = [
  {
    id: '1',
    name: 'Running',
    category: 'Cardio',
    intensity: 'Medium' as const,
    typicalDuration: 30,
    calorieRangeLow: 250,
    calorieRangeHigh: 350,
    description: 'Steady-paced running to build cardio endurance',
  },
  {
    id: '2',
    name: 'Cycling',
    category: 'Cardio',
    intensity: 'Medium' as const,
    typicalDuration: 45,
    calorieRangeLow: 300,
    calorieRangeHigh: 450,
    description: 'Cycling on roads or trails',
  },
  {
    id: '3',
    name: 'Swimming',
    category: 'Cardio',
    intensity: 'High' as const,
    typicalDuration: 30,
    calorieRangeLow: 350,
    calorieRangeHigh: 500,
    description: 'Full-body cardio workout in water',
  },
  {
    id: '4',
    name: 'Weight Training',
    category: 'Strength',
    intensity: 'High' as const,
    typicalDuration: 45,
    calorieRangeLow: 200,
    calorieRangeHigh: 350,
    description: 'Resistance training with weights',
  },
  {
    id: '5',
    name: 'Bodyweight Circuit',
    category: 'Strength',
    intensity: 'Medium' as const,
    typicalDuration: 30,
    calorieRangeLow: 200,
    calorieRangeHigh: 300,
    description: 'Pushups, squats, and bodyweight exercises',
  },
  {
    id: '6',
    name: 'Yoga Flow',
    category: 'Flexibility',
    intensity: 'Low' as const,
    typicalDuration: 45,
    calorieRangeLow: 100,
    calorieRangeHigh: 200,
    description: 'Vinyasa or hatha yoga practice',
  },
  {
    id: '7',
    name: 'Pilates',
    category: 'Flexibility',
    intensity: 'Medium' as const,
    typicalDuration: 30,
    calorieRangeLow: 150,
    calorieRangeHigh: 250,
    description: 'Core-focused flexibility training',
  },
  {
    id: '8',
    name: 'HIIT Training',
    category: 'HIIT',
    intensity: 'High' as const,
    typicalDuration: 20,
    calorieRangeLow: 250,
    calorieRangeHigh: 400,
    description: 'High-intensity interval training',
  },
  {
    id: '9',
    name: 'Basketball',
    category: 'Sports',
    intensity: 'High' as const,
    typicalDuration: 60,
    calorieRangeLow: 400,
    calorieRangeHigh: 600,
    description: 'Recreational or competitive basketball',
  },
  {
    id: '10',
    name: 'Tennis',
    category: 'Sports',
    intensity: 'Medium' as const,
    typicalDuration: 60,
    calorieRangeLow: 300,
    calorieRangeHigh: 500,
    description: 'Singles or doubles tennis',
  },
  {
    id: '11',
    name: 'Jump Rope',
    category: 'Cardio',
    intensity: 'High' as const,
    typicalDuration: 15,
    calorieRangeLow: 150,
    calorieRangeHigh: 250,
    description: 'High-intensity rope jumping',
  },
  {
    id: '12',
    name: 'Stretching Routine',
    category: 'Flexibility',
    intensity: 'Low' as const,
    typicalDuration: 20,
    calorieRangeLow: 50,
    calorieRangeHigh: 100,
    description: 'Static and dynamic stretching',
  },
];

export const FITNESS_GOALS = [
  'Lose Weight',
  'Build Muscle',
  'Improve Endurance',
  'Stay Active',
  'Train for Event',
  'General Fitness',
];

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Français' },
  { code: 'de', name: 'Deutsch' },
  { code: 'zh', name: '中文' },
  { code: 'ja', name: '日本語' },
];

export const MOTIVATIONAL_QUOTES = [
  'Every step counts. Keep moving!',
  "You're doing amazing! Keep it up!",
  'Progress, not perfection. You\'ve got this!',
  'Consistency is key to success!',
  'Your body can stand almost anything. It\'s your mind that you need to convince.',
  'The only bad workout is the one that didn\'t happen.',
  'Take care of your body. It\'s the only place you have to live.',
  'Success is the sum of small efforts repeated day in and day out.',
];

export const COLORS = {
  primary: '#777e93',
  secondary: '#f6f6f6',
  light: '#ffffff',
  dark: '#1a1a1a',
  cardDark: '#2d2d2d',
  success: '#10b981',
  warning: '#f59e0b',
  error: '#ef4444',
  info: '#3b82f6',
};

export const INTENSITY_COLORS = {
  Low: '#10b981',
  Medium: '#f59e0b',
  High: '#ef4444',
};
